# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 10
  batch_size: 8
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: ./../X-UMX/data/
  audio_chan: 2
  sample_rate: 44100
  seq_dur: 1.0
  samples_per_track: 64
  source_augmentations:
    - gain
    - channelswap
  sources:
    - bass
    - drums
    - vocals
    - other
